name: "Check for deprecated functions using staticheck GH action"
on:
  push:

jobs:
  lint-deprecated:
    name: Deprecated check using staticcheck
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
	  with:
		fetch-depth: 1
	- uses: dominikh/staticcheck-action@v1.2.0
	  with:
		version: "2022.1.1"
    args: >-
            --config=./.github/configs/staticcheck.conf