name: "Check for deprecated functions "
on:
  push:

jobs:
  deprecated-check-setup:
    name: Deprecated check
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3.4.0
      - name: set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v4
        with:
          go-version-file: ./.go-version
          cache: true
      - name: staticcheck
        run: |
          echo "Installing staticcheck"
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "Running staticcheck to look for deprecations"
          staticcheck ./... | grep deprecated


        
       
        
        

  