name: "Check Deprecations"

on:
  pull_request:
    # Runs on PRs to main
    branches:
      - main

jobs:
  deprecations-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v4
        with:
          go-version-file: ./.go-version
          cache: true
      - name: Check deprecations for files in diff
        run: |
          # Need to run this from base path and not from .github/scripts as staticcheck works 
          # only on packages
          ./.github/scripts/deprecations-checker.sh ${{ github.event.pull_request.base.ref }}