name: "Check for deprecated functions "

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    # Runs on PRs to main
    branches:
      - main

jobs:
  deprecated-check-setup:
    name: Deprecated check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v4
        with:
          go-version-file: ./.go-version
          cache: true
      - name: staticcheck to look for deprecations in diff
        run: |
          echo "Installing staticcheck"
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.2 #v0.4.2

          echo "Running staticcheck to look for deprecations"

          # run staticcheck
          staticcheck ./... | grep deprecated > staticcheckOutput.txt

          # get changed files names from the PR

          echo "Get filenames in the current PR"
          changedFiles=$(git --no-pager diff --name-only HEAD "$(git merge-base HEAD "origin/${{ github.event.pull_request.base.ref }}")")
          
          for val in ${changedFiles[@]}; do
            echo "$val changed"
          done

          # include deprecations details of only changed files in the PR
          echo "Find deprecations related to files in the PR"

          for fileName in ${changedFiles[@]}; do
            grep $fileName staticcheckOutput.txt >> tmpfile
          done

          # cleanup and update deprecations file
          mv tmpfile staticcheckOutput.txt

          # output deprecations

          echo "Results:"

          if [ -s staticcheckOutput.txt ]
          then
              echo "Use of deprecated function, variable, constant or field found"
              cat staticcheckOutput.txt 

              # output file clean up 
              rm -rf staticcheckOutput.txt  
              exit 1 
          else
              echo "Use of deprecated function, variable, constant or field not found"

              # output file clean up 
              rm -rf staticcheckOutput.txt  
          fi