name: "Check for deprecated functions "
on:
  push:

jobs:
  deprecated-check-setup:
    name: Deprecated check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ${{ steps.get-metadata.outputs.go-version }}
      - name: staticcheck
        run: |
          echo "Installing staticcheck"
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.2 #v0.4.2

          echo "Running staticcheck to look for deprecations"

          # run staticcheck
          staticcheck ./... | grep deprecated > staticcheckOutput.txt

          # get changed files names from the PR
          changedFiles=$(git diff --name-only origin/main)   

          # include deprecations details of only changed files in the PR
          for fileName in ${changedFiles[@]}; do
            grep $fileName staticcheckOutput.txt >> tmpfile
          done

          # cleanup and update deprecations file
          mv tmpfile staticcheckOutput.txt

          # output deprecations
          if [ -s staticcheckOutput.txt ]
          then
              echo "Use of deprecated function, variable, constant or field found"
              cat staticcheckOutput.txt 

              # output file clean up 
              rm -rf staticcheckOutput.txt  
              exit 1 
          else
              echo "Use of deprecated function, variable, constant or field not found"

              # output file clean up 
              rm -rf staticcheckOutput.txt  
          fi