name: "Check for deprecated functions "
on:
  push:

jobs:
  deprecated-check-setup:
    name: Deprecated check
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3.4.0
      - name: set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v4
        with:
          go-version-file: ./.go-version
          cache: true
      - name: staticcheck
        run: |
          echo "Installing staticcheck"
          go install honnef.co/go/tools/cmd/staticcheck@latest


          echo "Running staticcheck to look for deprecations"

          # use entire package name for packages
          ignoreList=("github.com/golang/protobuf/proto"
          "errwrap.Wrapf"
          "io/ioutil"
          "ptypes"
          ".RawRequestWithContext"
          ".RawRequest"
          "cloud.google.com/go/monitoring/apiv3"
          "crypto/dsa"
          "x509.ParseCRL"
          "ACL().Create"
          "ACL().Destroy" 
          "Statements.CreationStatements"
          "Statements.RevocationStatements"
          "Statements.RollbackStatements"
          "strings.Title"
          "connState.NegotiatedProtocolIsMutual")

          # run staticcheck
          staticcheck ./... | grep deprecated > staticcheckOutput.txt  

          # delete ignored values from the output
          for val in ${ignoreList[@]}; do
            grep -v $val staticcheckOutput.txt > tmpfile && mv tmpfile staticcheckOutput.txt
            rm -rf tmpfile
          done


          if [ -s staticcheckOutput.txt ]
          then
              echo "Use of deprecated function, variable, constant or field found"
              cat staticcheckOutput.txt 
              # output file clean up 
              rm -rf staticcheckOutput.txt  
              exit 1 
          else
              echo "Use of deprecated function, variable, constant or field not found"
              rm -rf staticcheckOutput.txt  
          fi